### ISSUE TITLE
ffmpeg non trovato

### ISSUE THREAD

**Issue by seaquake** [leoncvlt/raiplay-dl#1]
anche se ho ffmpeg installato (pip install ffmpeg) ricevo il seguente errore.
Purtroppo non sono pratico di phyton, commetto qualche errore?
Grazie per il supporto.

C:\Users\Seaquake\Desktop\raiplay-dl-master>python raiplay-dl.py -d rai https://www.raiplay.it/programmi/uncicloneinconvento
Download directory set to rai
Downloading show @ https://www.raiplay.it/programmi/uncicloneinconvento
Downloading set @ https://www.raiplay.it//programmi/uncicloneinconvento/ContentSet-9e0fd894-754c-463b-bf6d-c7edfc986ecb.json
Downloading title @ https://www.raiplay.it//video/2017/05/Un-ciclone-in-convento-S1E1---Tamburi-africani-e31ec4c4-478d-482e-b2f7-11655bc85ba4.json
[generic] relinkerServlet: Requesting header
[redirect] Following redirect to http://b2ushds2-vh.akamaihd.net/i/Italy/podcastcdn/raidue/Un_ciclone_in_convento/7141951_,800,1800,.mp4.csmil/master.m3u8?auth=daEaAd9bZaTdhbed_bAaYd_c5cgbMcgcrdt-bEqiKz-c0-GmsvsEs&aifp=V001
[generic] master: Requesting header
WARNING: Could not send HEAD request to http://b2ushds2-vh.akamaihd.net/i/Italy/podcastcdn/raidue/Un_ciclone_in_convento/7141951_,800,1800,.mp4.csmil/master.m3u8?auth=daEaAd9bZaTdhbed_bAaYd_c5cgbMcgcrdt-bEqiKz-c0-GmsvsEs&aifp=V001: HTTP Error 405: Method Not Allowed
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[download] Destination: master-master.mp4
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
Traceback (most recent call last):
  File "raiplay-dl.py", line 83, in <module>
    download(args.url, args.download_directory)
  File "raiplay-dl.py", line 33, in download
    download_show(url, download_dir)
  File "raiplay-dl.py", line 42, in download_show
    download_set(get_raiplay_url(block_set["path_id"]), download_dir)
  File "raiplay-dl.py", line 49, in download_set
    download_title(get_raiplay_url(episode["path_id"]), download_dir)
  File "raiplay-dl.py", line 76, in download_title
    ydl.download([video_url])
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2017, in download
    res = self.extract_info(
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 866, in process_ie_result
    return self.extract_info(ie_result['url'],
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 862, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1643, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1925, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1864, in dl
    return fd.download(name, info)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\downloader\external.py", line 35, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\downloader\external.py", line 227, in _call_downloader
    self.report_error('m3u8 download detected but ffmpeg or avconv could not be found. Please install one.')
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\downloader\common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python38-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

C:\Users\Seaquake\Desktop\raiplay-dl-master>pip install ffmpeg
Requirement already satisfied: ffmpeg in c:\users\seaquake\appdata\local\programs\python\python38-32\lib\site-packages (1.4)

**Comment by seaquake** [comment]
risolto ffmpeg.exe, ffplay.exe and ffprobe.exe devono essere nella stessa cartella

**Comment by leoncvlt** [comment]
In alternativa, aggiungi `ffmpeg.exe` alla variabile di sistema PATH: https://www.java.com/it/download/help/path.xml
